<?xml version="1.0"?>
<package format="3">
  <name>apds_lidar_clustering</name>
  <version>1.0.0</version>
  <description>ROS2 multi-LiDAR fusion package used by HYPERION.</description>
  <maintainer email="noreply@users.noreply.github.com">Yashika Sharma</maintainer>
  <license>Proprietary</license>
  <buildtool_depend>ament_cmake</buildtool_depend>
  <depend>rclpy</depend>
  <depend>sensor_msgs</depend>
  <depend>sensor_msgs_py</depend>
  <depend>laser_geometry</depend>
  <depend>tf2_ros</depend>
  <depend>tf2_sensor_msgs</depend>
  <exec_depend>ros2launch</exec_depend>
  <export><build_type>ament_cmake</build_type></export>
</package>
